ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of loop_sm-c_mass'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'GC_5 = ', GC_5
      WRITE(*,2) 'R2_GGHc = ', R2_GGHC
      WRITE(*,2) 'R2_GGHb = ', R2_GGHB
      WRITE(*,2) 'R2_GGHt = ', R2_GGHT
      WRITE(*,2) 'GC_33 = ', GC_33
      WRITE(*,2) 'GC_34 = ', GC_34
      WRITE(*,2) 'GC_37 = ', GC_37
