ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of sm-full'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'GC_1 = ', GC_1
      WRITE(*,2) 'GC_2 = ', GC_2
      WRITE(*,2) 'GC_41 = ', GC_41
      WRITE(*,2) 'GC_42 = ', GC_42
      WRITE(*,2) 'GC_44 = ', GC_44
      WRITE(*,2) 'GC_45 = ', GC_45
      WRITE(*,2) 'GC_50 = ', GC_50
      WRITE(*,2) 'GC_51 = ', GC_51
      WRITE(*,2) 'GC_58 = ', GC_58
      WRITE(*,2) 'GC_69 = ', GC_69
      WRITE(*,2) 'GC_72 = ', GC_72
      WRITE(*,2) 'GC_81 = ', GC_81
      WRITE(*,2) 'GC_84 = ', GC_84
      WRITE(*,2) 'GC_100 = ', GC_100
      WRITE(*,2) 'GC_101 = ', GC_101
      WRITE(*,2) 'GC_103 = ', GC_103
      WRITE(*,2) 'GC_104 = ', GC_104
